###🔹 Test API Allergy
GET http://localhost:3000/api/allergy/test HTTP/1.1

###🔹 Ottieni tutte le allergie
GET http://localhost:3000/api/allergy/ HTTP/1.1

###🔹 Ottieni allergie per username
GET http://localhost:3000/api/allergy/marco_bruno HTTP/1.1

###🔹 Inserisci una nuova allergia
POST http://localhost:3000/api/allergy/marco_bruno HTTP/1.1
Content-Type: application/json
{
  "allergy": "glutine"
}
###🔹 Aggiorna un'allergia per username
PUT http://localhost:3000/api/allergy/marco_bruno/soia HTTP/1.1
Content-Type: application/json
{
    "allergy": "lattosio"
}
###🔹 Elimina un'allergia per username
DELETE http://localhost:3000/api/allergy/marco_bruno/glutine HTTP/1.1
